# Netlify Configuration File
[build]
  publish = "."

# Supabase Reverse Proxy to bypass ISP and firewall blocks in Myanmar & worldwide
[[redirects]]
  from = "/supabase/*"
  to = "https://prqwwuxfpynmzdvaoesh.supabase.co/:splat"
  status = 200
  force = true

# Recommended HTTP security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
